import { tag, oneOf, space0, pair } from "src";

export const questionMark = tag('"');
export const apostrophe = tag("'");
export const minus = tag("-");
export const plus = tag("+");
export const underscore = tag("_");
export const hexPrefix = tag("0x");
export const octPrefix = tag("0o");
export const binPrefix = tag("0b");
export const e = oneOf("eE");
export const inf = tag("inf");
export const nan = tag("nan");
export const decimalPoint = tag(".");
export const colon = tag(":");
export const hyphen = tag("-");
export const arrayOpen = tag("[");
export const arrayClose = tag("]");
export const comma = tag(",");
export const inlineTableOpen = tag("{");
export const inlineTableClose = tag("}");
export const equal = tag("=");
export const stdTableOpen = pair(tag("["), space0);
export const stdTableClose = pair(space0, tag("]"));
export const arrayTableOpen = pair(tag("[["), space0);
export const arrayTableClose = pair(space0, tag("]]"));
export const mlBasicStringDelim = tag('"""');
export const escape = tag("\\");
export const mlLiteralStringDelim = tag("'''");
